### PR TITLE
Added changelog for 0.5.0

### PR DESCRIPTION
**Pull request by Nyholm**
FYI @rdotter

### CODE REVIEW

**Comment by rdotter** [comment]
@Nyholm thanks for this preparement of this version :-)

**Comment by Nyholm** [comment]
Have you tested it? Does it work for you?

**Comment by rdotter** [comment]
@Nyholm I just tested this with the current master. And when I send an example message with incorrect data within the JSON, there will be an `[Symfony\Component\Messenger\Exception\MessageDecodingFailedException]` exception thrown.
The consumer is stopped, when I restart the consumer, the message is acknowledged.

**Comment by Nyholm** [comment]
Cool. Thank you

**Pull request merged**
