### PR TITLE
implement __serialize and __unserialize

### PR DESCRIPTION
**Pull request by mahdi-khanzadi**
in order to update to php8.1 we need this changes.

### CODE REVIEW

**Comment by mhabibi** [comment]
Any chance getting this released?

**Comment by michael-sfx** [comment]
Oh yes that would be great.
https://php.watch/versions/8.1/serializable-deprecated

**Comment by TomBrouws** [comment]
I would like to add a +1 on the above

**Comment by HEKET313** [comment]
+1

**Comment by sroze** [comment]
Closed by https://github.com/sroze/messenger-enqueue-transport/pull/115.

**Pull request closed without merging**
