### PR TITLE
Prepare for release 0.4.0

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by dannyvw** [comment]
@Nyholm When will this be released?

**Comment by Nyholm** [comment]
If you try it out and confirm that it is working as expected, I'll be happy to release it today

**Comment by Steveb-p** [comment]
@dannyvw 

you can use Composer's functionality to overwrite packages to temporarily provide your own fork instead of a package: https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

> Loading a package from a VCS repository
There are a few use cases for this. The most common one is maintaining your own fork of a third party library. If you are using a certain library for your project and you decide to change something in the library, you will want your project to use the patched version. If the library is on GitHub (this is the case most of the time), you can simply fork it there and push your changes to your fork. After that you update the project's composer.json. All you have to do is add your fork as a repository and update the version constraint to point to your custom branch. In composer.json, you should prefix your custom branch name with "dev-".

So, in your case it might be:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/Nyholm/messenger-enqueue-transport"
        }
    ],
    "require": {
        "sroze/messenger-enqueue-transport": "^0.4.0 | dev-release-040"
    }
}
```

**Comment by dannyvw** [comment]
@Nyholm Thx, we will test it tomorrow i think.

@Steveb-p I have already configured that. But it would be nice to have a release :)

**Comment by Steveb-p** [comment]
@dannyvw 

giphy

**Comment by Nyholm** [comment]
Just try installing dev-master, that will allow you to run your tests.
There is no need to download my fork.. since that only includes the changelog.md.

**Comment by dannyvw** [comment]
@Nyholm No issues on our side (2 projects)

**Comment by Nyholm** [comment]
Thank you

**Comment by Nyholm** [comment]
https://github.com/sroze/messenger-enqueue-transport/releases/tag/0.4.0

**Pull request merged**
