### PR TITLE
Allow Symfony 7

### PR DESCRIPTION
**Pull request by andrewmy**
Let's install this on modern apps too!

This repo appears to not have a CI but tested it with a downstream internal project and it works.

### CODE REVIEW

**Comment by andrewmy** [comment]
@Nyholm could you please take a look? Thanks!

**Comment by Nyholm** [comment]
Thank you @andrewmy, you are a star. 

Let's merge this now, but maybe we should add CI (and drop some PHP and SF versions) before we tag it. What do you think?

**Comment by andrewmy** [comment]
@Nyholm alright let's try: https://github.com/sroze/messenger-enqueue-transport/pull/127

**Comment by Nyholm** [comment]
Thank you for your work
I just released 0.8.0

https://github.com/sroze/messenger-enqueue-transport/releases/tag/0.8.0

**Pull request merged**
